agent: homework.class calibrate.class

homework.class: homework.java
	javac homework.java

calibrate.class: calibrate.java
	javac calibrate.java

run: homework.class
	java homework

calibrate: calibrate.class
	java calibrate

newgame:
